//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDPR.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventHub
    {
        public string LongName { get; set; }
        public int Position { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime CheckPoint { get; set; }
        public string EventHubName { get; set; }
        public string PartitionId { get; set; }
    }
}
