//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDPR.Util
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GDPRDatabaseEntities : DbContext
    {
        public GDPRDatabaseEntities()
            : base("name=GDPRDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Processor> Processors { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<SubjectApplication> SubjectApplications { get; set; }
        public virtual DbSet<SubjectApplicationConsent> SubjectApplicationConsents { get; set; }
        public virtual DbSet<SubjectRequest> SubjectRequests { get; set; }
        public virtual DbSet<SubjectRequestApplication> SubjectRequestApplications { get; set; }
        public virtual DbSet<EventHub> EventHubs { get; set; }
    }
}
