//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDPR.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectApplicationConsent
    {
        public System.Guid SubjectApplicationConsentId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public System.Guid SubjectId { get; set; }
        public System.DateTime ConsentDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
