//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDPR.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectRequestApplication
    {
        public System.Guid SubjectRequestApplicationResultId { get; set; }
        public System.Guid SubjectRequestId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public string Status { get; set; }
        public string DataExportLink { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual SubjectRequest SubjectRequest { get; set; }
        public virtual SubjectRequest SubjectRequest1 { get; set; }
    }
}
